### ISSUE TITLE
Contributte

### ISSUE THREAD

**Issue by f3l1x** [contributte/guzzlette#8]
I have a crazy idea. I like an idea, I like this package and I also love this name. :-D

What about move this package under contributte and work on it together?

@matyx

**Comment by matyx** [comment]
Not crazy idea at all, I was thinking about it too :) lets discuss it on pehapkari slack

**Comment by f3l1x** [comment]
Some summary from me.

1) PSR-4 namespaces. It's standard that Nette extensions has *Extension* in name and they are in DI namespace (src/DI/GuzzletteExtension).

2) You shoud *not* to check that class exists (`!class_exists('Tracy\Debugger')`), rather use config (`debug: true/false`).

3) Guzzlette and ::createGuzzletteClient is little bit confusing, rather to use ClientFactory and Client. Guzzlette is name of this package right?

4) You should *not* use `Tracy\Debugger::timer`, this addon should have a optional dependency on Tracy.

5) It's better to have more files for each exception, not just one file as Nette has.

6) It might be better to have a Tracy<> in their own namespace.

7) I think that this addon could have only 1 primary dependency guzzle. Nette\DI and Tracy could be require-dev dependencies and other ones are not needed. 

-----

What do you think?

**Comment by f3l1x** [comment]
Hi @matyx. How about to move it under contributte org in this year? :-) I looks good to me.

**Comment by f3l1x** [comment]
Done! :-D
